version: '3.8'

services:
  postgres:
    container_name: postgres-sql
    image: postgres
    volumes:
      - pg_data:/usr/share/postgres/data
    networks:
      - groceries-shop-network
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: groceries-shop-db

  groceries-shop:
    container_name: groceries-shop
    image: amileva/groceries_shop:1.0
    environment:
      DATABASE_URL: jdbc:postgresql://postgres-sql:5432/groceries-shop-db
    ports:
      - '8080:8080'
    networks:
      - groceries-shop-network

volumes:
  pg_data:
    name: groceries-shop-postgres-data-11.10

networks:
  groceries-shop-network:
    driver: bridge