spring:
  application:
    name: groceries-shop

  datasource:
    username: postgres
    password: postgres
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/groceries-shop-db}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  mvc:
    hiddenmethod:
      filter:
        enabled: true


  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs